export const CREATE_POINT = 'CREATE_POINT';
export const REMOVE_POINT = 'REMOVE_POINT';
export const UPDATE_POINT = 'UPDATE_POINT';
export const INCREMENT_LIKE = 'INCREMENT_LIKE';
export const INCREMENT_LIKE_ALL = 'INCREMENT_LIKE_ALL';
export const UPDATE_TITLE = 'UPDATE_TITLE';
